apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: registry.gitlab.com/dostream1/application/backend/shopping:main # Replace with your image and tag
          ports:
            - containerPort: 8003
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"  # Adjust the CPU limit as needed
            requests:
              cpu: "100m"  # Adjust the CPU request as needed

