apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: your-shopping-image:$(TAG) # Replace with your image and tag
          ports:
            - containerPort: 8003
          # Add volume mounts and resources as needed
          resources:
            limits:
              memory: "512Mi"  # Adjust the memory limit as needed
              cpu: "0.5"        # Adjust the CPU limit as needed
