name: CI/CD Pipeline


on:
  push:
    branches:
      - main

jobs:

  code-scan:
    name: Code-Scan
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit
    
  build:
    needs: code-scan
    name: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      image-tag: "my-tag1"

  trivy-scan:
    needs: build
    name: Trivy
    uses: ./.github/workflows/trivy-scan.yml
    secrets: inherit
    with:
      image-tag: "my-tag1"

  deploy-dev:
    needs: [build, trivy-scan] 
    name: Deploy-Dev
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      image-tag: "my-tag1"
      env: "dev"

  test-dev:
    name: test-dev
    needs: deploy-dev
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      env: "dev"

  deploy-stg:
    needs: test-dev
    name: Deploy-Stg
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      image-tag: "my-tag1"
      env: "stg"
      
  test-stg:
    name: test-stg
    needs: deploy-stg
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      env: "stg"
    
  deploy-prod:
    needs: test-stg
    name: Deploy-Prod
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      image-tag: "my-tag1"
      env: "prod"

  test-prod:
    name: deploy-prod
    needs: deploy-prod
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      env: "stg"
