name: SAST for Node.js

on:
  workflow_dispatch:
  workflow_call:

jobs:
  SAST-CodeQL:
    name: Build and SAST CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build with npm
        run: npm run build

      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  spotbugs:
    name: SAST SpotBugs
    needs: [SAST-CodeQL]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SpotBugs action (modify as needed for Node.js)
        run: echo "Run your SpotBugs or alternative Node.js security scanning here"

  semgrep:
    needs: [SAST-CodeQL]
    name: SAST Semgrep
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    container:
      image: returntocorp/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep (modify as needed for Node.js)
        run: semgrep ci -v -o results.sarif --sarif || true
        env:
          SEMGREP_RULES: p/default p/security-audit p/r2c-security-audit p/cwe-top-25 p/owasp-top-ten

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: semgrep.sarif
          path: ${{ github.workspace }}/results.sarif

      - name: Upload analysis results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2.1.28
        with:
          sarif_file: ${{ github.workspace }}/results.sarif
