name: Sonarqube pipeline
on: workflow_call

jobs:
    Docker-Scan:
        runs-on: ubuntu-latest
        steps:
          - name: Check out code
            uses: actions/checkout@v2
    
          - name: Install SSH client
            run: apt-get install openssh-client -y
    
          - name: Set up SSH key for Docker scan
            run: |
              eval $(ssh-agent -s)
              echo -n "$SSH_PRIVATE_KEY_INTERNAL_TRIVY" | tr -d '\r' | ssh-add -
              mkdir -p ~/.ssh
              chmod 700 ~/.ssh
              ssh-keyscan ${{ secrets.SSH_HOST_TRIVY }} >> ~/.ssh/known_hosts
              chmod 644 ~/.ssh/known_hosts
    
          - name: Run Trivy scan
            run: |
              echo ${{ secrets.CI_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin ${{ secrets.CI_REGISTRY }}
              trivy image --severity CRITICAL,HIGH,MEDIUM --format json -o trivy-results.json nexus.corp.4sconsult.com/Buy-it-customer-service:latest
            env:
              CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
              CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
    
          - name: Upload Trivy results
            uses: actions/upload-artifact@v2
            with:
              name: trivy-results
              path: trivy-results.json
